# docker-compose.yml
version: '3.8'
services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-network

  # Example app service
  fusionauth:
    image: fusionauth/fusionauth-app:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.your-app.rule=Host(`auth.almahdi.cloud`)"
      - "traefik.http.routers.your-app.entrypoints=web"
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge