import { Injectable, NotFoundException } from "@nestjs/common";
import { db } from "src/db/client";
import { conversationAI } from "src/db/schema/chat.schema";
import {eq} from "drizzle-orm" 
import { users } from "src/db/schema/profiles.schema";
import * as puppeteer from 'puppeteer';
import * as fs from 'fs';
import * as path from 'path';


@Injectable()
export class DiagnosesPdfService {
async generateDiagnosisPdf(conversationId: number): Promise<string> {
  const diagnosesInfo = await db
    .select()
    .from(conversationAI)
    .where(eq(conversationAI.id, conversationId));

  if (diagnosesInfo.length === 0) {
    throw new Error('Conversation not found');
  }
 

  const conversation = diagnosesInfo[0];

  const userResult = await db
    .select()
    .from(users)
    .where(eq(users.fusionAuthId, conversation.userId));

  if (userResult.length === 0) {
    throw new Error('User not found');
  }

  const user = userResult[0];

let toothImageBase64 = '';
  if (conversation.image_path) {
    

    const relativePath = conversation.image_path.startsWith('/') 
      ? conversation.image_path.slice(1) 
      : conversation.image_path;

    const imageFullPath = path.join(process.cwd(), relativePath);

    console.log('Image Path Check:', imageFullPath); 

    if (fs.existsSync(imageFullPath)) {
      toothImageBase64 = fs.readFileSync(imageFullPath, {
        encoding: 'base64',
      });
    } else {
        console.warn('Image not found at path:', imageFullPath);
    }
  }

  const html = `
  <html>
    <head>
      <meta charset="UTF-8" />
      <style>
        body {
          font-family: Arial, sans-serif;
          padding: 30px;
          color: #222;
        }
        h1 {
          text-align: center;
        }
        .card {
          border: 1px solid #ccc;
          border-radius: 8px;
          padding: 15px;
          margin-bottom: 20px;
        }
        .label {
          font-weight: bold;
        }
        img {
          max-width: 350px;
          margin-top: 10px;
          border: 1px solid #ddd;
        }
        .footer {
          margin-top: 40px;
          font-size: 12px;
          color: #666;
        }
      </style>
    </head>
    <body>

      <h1>Dental AI Diagnosis Report</h1>

      <div class="card">
        <p><span class="label">Patient Name:</span> ${user.firstName ?? ''} ${user.lastName ?? ''}</p>
        <p><span class="label">Gender:</span> ${user.gender}</p>
        <p><span class="label">Birth Year:</span> ${user.birthYear}</p>
        <p><span class="label">Phone:</span> ${user.phoneNumber}</p>
      </div>

      <div class="card">
        <p><span class="label">Final Speciality:</span> ${conversation.specialityE}</p>
      </div>

      ${
        toothImageBase64
          ? `<div class="card">
               <p class="label">Tooth Image</p>
               <img src="data:image/jpeg;base64,${toothImageBase64}" />
             </div>`
          : ''
      }

      <div class="footer">
        This diagnosis was generated by an AI system and must be reviewed by a licensed dentist.
      </div>

    </body>
  </html>
  `;

  const browser = await puppeteer.launch({
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: 'networkidle0' });

  const pdfFileName = `diagnosis_${conversationId}.pdf`;
  const pdfPath = path.join(process.cwd(), 'uploads', pdfFileName);

  await page.pdf({
    path: pdfPath,
    format: 'A4',
    printBackground: true,
  });

  await browser.close();


  return pdfPath;
}
async getPdfPath(conversationId: number): Promise<string> {
    
    const result = await db
      .select({
        pdfPath: conversationAI.pdfReportPath
      })
      .from(conversationAI)
      .where(eq(conversationAI.id, conversationId));

    if (result.length === 0) {
      throw new NotFoundException('Conversation not found');
    }

    const savedPath = `uploads/${result[0].pdfPath}`;
console.log(savedPath)
    if (!savedPath) {
      throw new NotFoundException('PDF report has not been generated for this conversation yet.');
    }

    if (!fs.existsSync(savedPath)) {
      throw new NotFoundException('File not found on server storage.');
    }
   console.log(savedPath)
    return savedPath;
  }
}